### ISSUE TITLE
DFU Apple Silicon Macs with macvdmtool

### ISSUE THREAD

**Issue by jeolsen** [discentem/blog-content#3]
Do the steps for "DFU Apple Silicon Macs with macvdmtool" still work on macOS 12.2.1?  I'm testing this on a 2021 MacBook Pro 16" M1 Pro system and getting the following error:

% sudo ./macvdmtool dfu          
Mac type: MacBookPro15,1
Looking for HPM devices...
Found: IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG1@1,1/IOPP/UPSB@0/IOPP/DSB0@0/IOPP/NHI0@0/AppleThunderboltHAL/AppleThunderboltNHIType3/IOThunderboltController/IOThunderboltPort@7/IOThunderboltSwitchType3/IOThunderboltIECSNub/AppleHPMIECS
Connection: Source
Status: APP 
Unlocking...  Failed.
Trying to reset... OK.
Unlocking...  Failed.
Exiting DBMa mode... Failed
Failed to unlock device

The macvdmtool github states:
To have access to the serial console device on macOS Monterey (12), you need to disable the AppleSerialShim extension.

But i didn't see that in your guide or on Mr. Macintosh's youtube, so not sure if that is something new.  Hoping that is not required since that would make the process unusable for my scenario.

Thanks

**Comment by discentem** [comment]
Glad to find out someone reads my blog haha! 

I asked a colleague and they reported they were able to DFU 12.3b4 without needing to change boot security. I will try to test in the next few days and let you know if I can reproduce their success.

**Comment by discentem** [comment]
Per MrMacintosh, I have [removed the step in my blog post where I said you need to put the target device in serial mode](https://github.com/discentem/blog-content/commit/4fab5a5a8d75efe96e7fb72994999516953fef3f) (as this was apparently unnecessary). I am in the process of restoring a machine to 12.3 right now, will report if it's successful in a bit

**Comment by discentem** [comment]
Confirmed, was able to restore a target m1 machine to 12.3. I'd make sure that you are using the correct ports on both sides (not all usb ports can act as a dfu port)
