### ISSUE TITLE
Progress bar stuck on cfgutil restore

### ISSUE THREAD

**Issue by francis2054** [discentem/blog-content#8]
No idea if this is a recurring issue, but i used the cfgutil restore command for the first time, and at 49% done in terminal, the DFU restore was already done on the macbook, the terminal progress is still stuck after having pulled the cable
![image](https://github.com/discentem/blog-content/assets/10989018/f0263d58-ba69-4c3c-ae78-6154ca93dc33)

I suppose im posting this issue to update again once ive done another restore

**Comment by francis2054** [comment]
A bit after pulling the cable i got this, so it was still active in some way 
![image](https://github.com/discentem/blog-content/assets/10989018/6eb5360a-8d6b-4706-a841-ffc89fc3a272)

**Comment by discentem** [comment]
Somehow missed this issue, sorry about that! I'd say that this is out of scope unless you want to make a `known failure scenarios` section the post as we don't control the behavior of cfgutil.
